sudo: false
language: php

php:
  - 7.0

matrix:
  fast_finish: true

install:
  - composer self-update

before_script:
  - composer install --no-interaction --no-scripts

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover